### ISSUE TITLE
ipwnder_lite library issue under ios.

### ISSUE THREAD

**Issue by userse31** [LukeZGD/Legacy-iOS-Kit#327] opened 2023-09-20 18:13 UTC
Under iOS (atleast 14.4) ipwnder_lite exits immediately due to "libnghttp2.14.dylib" not being loaded.

-Log from Cr4shed-

Date: 9/20/23, 2:10 PM
Process: ipwnder_lite
Bundle id: (null)
Device: iPhone 7, iOS 14.4

Exception type: EXC_SOFTWARE (SIGABRT)
Exception subtype: EXC_UNIX_ABORT
Exception codes: 0x0000000000010002, 0x0000000000000000
Culprit: Unknown
Termination Reason: Library not loaded: /usr/lib/libnghttp2.14.dylib
  Referenced from: /usr/lib/libcurl.4.dylib
  Reason: no suitable image found.  Did find:
	/usr/lib/libnghttp2.14.dylib: code signature in (/usr/lib/libnghttp2.14.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
	/usr/lib/libnghttp2.14.dylib: code signature in (/usr/lib/libnghttp2.14.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.

Triggered by thread: 0
Thread name: 
Call stack:
0   cy-v60D8z.dylib               	0x00000001030c93e8 0x103078000 + 332776     
1   cy-v60D8z.dylib               	0x00000001030d0ca4 0x103078000 + 363684     
2   cy-v60D8z.dylib               	0x00000001030d0cd4 0x103078000 + 363732     
3   cy-v60D8z.dylib               	0x000000010307ce1c 0x103078000 + 19996      
4   cy-v60D8z.dylib               	0x000000010307fc48 0x103078000 + 31816      
5   cy-v60D8z.dylib               	0x0000000103079208 0x103078000 + 4616       
6   cy-v60D8z.dylib               	0x0000000103079038 0x103078000 + 4152       

Register values:
PC: 0x0                 LR: 0x0                 CPSR: 0x0
x0: 0x0                 x1: 0x0                 x2: 0x0
x3: 0x0                 x4: 0x0                 x5: 0x0
x6: 0x0                 x7: 0x0                 x8: 0x0
x9: 0x0                 x10: 0x0                x11: 0x0
x12: 0x0                x13: 0x0                x14: 0x0
x15: 0x0                x16: 0x0                x17: 0x0
x18: 0x0                x19: 0x0                x20: 0x0
x21: 0x0                x22: 0x0                x23: 0x0
x24: 0x0                x25: 0x0                x26: 0x0
x27: 0x0                x28: 0x0

Loaded images:
0: /usr/local/bin/ipwnder_lite
1: /usr/lib/libcurl.4.dylib
2: /Library/Caches/cy-v60D8z.dylib
3: /usr/lib/system/libdispatch.dylib
4: /usr/lib/system/libdyld.dylib
5: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
6: /usr/lib/system/libsystem_info.dylib
7: /usr/lib/system/libsystem_c.dylib
8: /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
9: /usr/lib/system/libsystem_malloc.dylib
10: /usr/lib/system/libsystem_networkextension.dylib
11: /usr/lib/libobjc.A.dylib
12: /usr/lib/libc++.1.dylib
13: /usr/lib/libc++abi.dylib
14: /usr/lib/system/libsystem_trace.dylib
15: /usr/lib/system/libsystem_notify.dylib
16: /usr/lib/system/libcorecrypto.dylib
17: /usr/lib/system/libsystem_asl.dylib
18: /usr/lib/system/libsystem_symptoms.dylib
19: /usr/lib/system/libsystem_kernel.dylib
20: /usr/lib/libSystem.B.dylib
21: /usr/lib/libz.1.dylib
22: /usr/lib/system/libcache.dylib
23: /usr/lib/system/libcommonCrypto.dylib
24: /usr/lib/system/libcompiler_rt.dylib
25: /usr/lib/system/libcopyfile.dylib
26: /usr/lib/system/liblaunch.dylib
27: /usr/lib/system/libmacho.dylib
28: /usr/lib/system/libremovefile.dylib
29: /usr/lib/system/libsystem_blocks.dylib
30: /usr/lib/system/libsystem_collections.dylib
31: /usr/lib/system/libsystem_configuration.dylib
32: /usr/lib/system/libsystem_containermanager.dylib
33: /usr/lib/system/libsystem_coreservices.dylib
34: /usr/lib/system/libsystem_darwin.dylib
35: /usr/lib/system/libsystem_dnssd.dylib
36: /usr/lib/system/libsystem_featureflags.dylib
37: /usr/lib/system/libsystem_m.dylib
38: /usr/lib/system/libsystem_platform.dylib
39: /usr/lib/system/libsystem_product_info_filter.dylib
40: /usr/lib/system/libsystem_pthread.dylib
41: /usr/lib/system/libsystem_sandbox.dylib
42: /usr/lib/system/libunwind.dylib
43: /usr/lib/system/libxpc.dylib

{"ProcessBundleID":"","ProcessName":"ipwnder_lite","Culprit":"Unknown"}

**Comment by userse31** [comment] 2023-09-20 18:32
Okay, so running "ldid -S /usr/libnghttp2.14.dylib" seems to resolve the issue.

**Comment by LukeZGD** [comment] 2023-09-21 00:37
Depending on the jailbreak you use (Odysseyra1n/Taurine/checkra1n/unc0ver): libnghttp2 is provided by Procursus/Elucubratus. The last time I tested was with Taurine and works fine there, so maybe a reinstall fixes it..? Though the issue is already resolved with ldid, that's a pretty weird issue

**Closed by LukeZGD** 2023-09-21 00:37 UTC

**Comment by userse31** [comment] 2023-09-21 20:47
It did work though!

Also, it's nice not having to costantly unplug and plug the phone in so that it shows up under linux!
