### ISSUE TITLE
Patcyh Error, ios 6.0 error

### ISSUE THREAD

**Issue by hoanmaster321** [LukeZGD/Legacy-iOS-Kit#318] opened 2023-08-28 11:41 UTC
I dowgrade ios 6.x.x iphone 5 (5,1)  iboot 7.x.x

ios 6.0 - no jailbreak - back screen not boot 
6.0 - 6.1.3 ( i test) jailbreak , login cydia tweak Patcyh only remover it is ios >= 8.3 , if remove Patcyh iphone backscreen

**Comment by LukeZGD** [comment] 2023-08-29 11:05
I have tested a few times on 7.x and lower, and it all seem to work just fine with Patcyh getting removed, so I'm unable to reproduce this issue.. I'm not sure on where to proceed from here, so I will be closing this issue now (for now)

**Closed by LukeZGD** 2023-08-29 11:05 UTC
