### ISSUE TITLE
iPhone 4 CDMA 3,3 only shows iOS 7.1.2 and nothing else for restore/downgrade 

### ISSUE THREAD

**Issue by XthemastaX** [LukeZGD/Legacy-iOS-Kit#302] opened 2023-07-03 01:18 UTC
I have an iPhone 4 CDMA 3,3 and despite the phone being supported to downgrade to iOS 5/6, I am unable to get anything lower than 7.1.2. I use MacOS and have successfully gotten an iPhone 4 GSM to 4.3.5 and iPhone 4S GSM/CDMA to 6.1.3. Any insight as to why this is the case? Thank you in advance!

**Comment by LukeZGD** [comment] 2023-07-03 01:21
What version of Legacy iOS Kit do you have? The option `powdersn0w (any iOS)` should show up just fine in the `Restore/Downgrade` menu

**Comment by XthemastaX** [comment] 2023-07-03 01:40
It was foolish of me to not check, my bad. I had used a dated version (23.06.23). I just got the newest version now and attempted to try again. Now it's saying the ipsw is unable to be verified. I redownloaded it from ipsw.me and it still says it. I tried anyway and it almost finishes but fails to retrieve device serial number.

**Comment by LukeZGD** [comment] 2023-07-03 01:45
failed to retrieve device serial number means that the target version you're trying to downgrade is not compatible with your device, you need to try a newer ios version.

as for the verifying fail, that is because ipsw.me has wrong hashes for some ios 5.x ipsws, i'll be fixing them soon

**Comment by XthemastaX** [comment] 2023-07-03 01:59
Thanks for the insight. Kind of bummed out this 8GB 3,3 I got only works with 6. Hopefully it runs well on it with legacy apps and games.

**Comment by LukeZGD** [comment] 2023-07-03 02:00
oh, it's an 8gb model.. yeah those are very likely to be incompatible with ios 5. anyways, the issue is resolved so i'm closing this now

**Closed by LukeZGD** 2023-07-03 02:00 UTC
